# Generated by Django 3.2.8 on 2021-10-09 21:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coctail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('instructions', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('optional', models.TextField()),
                ('glass', models.CharField(choices=[('HI', 'Highball'), ('LO', 'Lowball'), ('CT', 'Coctail'), ('ST', 'Shot'), ('WN', 'Wine'), ('CH', 'Champagne')], default='HI', max_length=2)),
                ('method', models.CharField(choices=[('SH', 'Shake'), ('ST', 'Stir'), ('BD', 'Build'), ('MD', 'Muddle'), ('TH', 'Throw')], default='SH', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('is_available', models.BooleanField(default=False)),
                ('price_per_l', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('is_available', models.BooleanField(default=False)),
                ('price_per_l', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('coctail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coctail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='coctail',
            name='ingredients',
            field=models.ManyToManyField(through='api.Recipe', to='api.Ingredient'),
        ),
        migrations.AddField(
            model_name='coctail',
            name='styles',
            field=models.ManyToManyField(related_name='coctails', to='api.Style'),
        ),
    ]
