# Generated by Django 3.2.8 on 2021-10-09 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211010_0001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Style',
        ),
    ]
