# Generated by Django 3.2.8 on 2021-10-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coctail',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='coctail',
            name='optional',
            field=models.TextField(blank=True),
        ),
    ]
