# Generated by Django 3.2.8 on 2021-10-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211010_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coctail',
            name='style',
            field=models.CharField(choices=[('SR', 'Sour'), ('CR', 'Creamy'), ('SF', 'Spirit-Forward'), ('CH', 'Champagne'), ('HI', 'Highball'), ('SW', 'Sweet'), ('FR', 'Fruity'), ('SP', 'Spicy'), ('SH', 'Shot'), ('OT', 'Other')], default='SR', max_length=2),
        ),
    ]
