# Generated by Django 3.2.8 on 2021-10-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_coctail_glass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coctail',
            name='method',
            field=models.CharField(choices=[('SH', 'Shake'), ('ST', 'Stir'), ('BD', 'Build'), ('MD', 'Muddle'), ('TH', 'Throw'), ('SW', 'Swizzle')], default='SH', max_length=2),
        ),
        migrations.AlterField(
            model_name='coctail',
            name='style',
            field=models.CharField(choices=[('SR', 'Sour'), ('CR', 'Creamy'), ('SF', 'Spirit-Forward'), ('CH', 'Champagne'), ('HI', 'Highball'), ('SH', 'Shot'), ('OT', 'Other')], default='SR', max_length=2),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
