# Generated by Django 3.2.8 on 2021-10-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211012_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coctail',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
